export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
export const CART_LIST="CART_LIST"
export const EMPTY_CART="EMPTY_CART"
export const REMOVE_ID="REMOVE_ID"
export const ADD_ID="ADD_ID"
export const ADD_CATEGORY="ADD_CATEGORY"
